# Generated by Django 3.2.8 on 2021-11-09 22:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('style_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('clark_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Clothing_Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarkclothes.brand')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarkclothes.size')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarkclothes.style')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarkclothes.type')),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarkclothes.user')),
            ],
        ),
    ]
