# Generated by Django 3.2.8 on 2021-11-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarkclothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='first name last name', max_length=500),
        ),
    ]
