# Generated by Django 3.2.8 on 2021-11-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarkclothes', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing_item',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Firstname Lastname', max_length=500),
        ),
    ]
