# Generated by Django 3.2.8 on 2021-11-24 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clarkclothes', '0004_availablity'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing_item',
            name='status',
            field=models.ForeignKey(default='Available', on_delete=django.db.models.deletion.CASCADE, to='clarkclothes.availablity'),
        ),
    ]
