# Generated by Django 3.2.8 on 2021-11-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarkclothes', '0005_clothing_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing_item',
            name='image',
            field=models.ImageField(default='null', upload_to='images/'),
        ),
    ]
